#!/bin/sh

set -o errexit
set -o nounset
set -o pipefail

echo Begin

echo
echo Cloning repo for update
echo

git clone example-repo example-repo-updated

echo
echo Copying updated YAML to repo
echo

cp knative-service-updated/service.yaml example-repo-updated/services/rendered/service.yaml

echo
echo Committing changes
echo

cd example-repo-updated

git add services/rendered/service.yaml

git status --verbose

git commit  -m "Update rendered service YAML." \
            -m "This commit is made automatically." \
            -m "[skip ci]"

git --no-pager log -1


echo
echo Done.
echo
