platform: linux

image_resource:
    type: registry-image
    source:
        repository: everpeace/curl-jq

inputs:
- name: knative-service
- name: example-repo

run:
    path: example-repo/concourse/tasks/test-reachability/run
